version: 2
jobs:
  build:
    working_directory: /tmp/workspace
    docker:
      - image: node:latest

    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "NPM v$(npm --version)"
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /tmp/workspace/node_modules
